__include__: [
  '../deim_dfine/dfine_hgnetv2_l_coco.yml',
  '../base/deim.yml'
]

output_dir: ./outputs/table4_cost_only
find_unused_parameters: true

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000025
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epoches: 58
flat_epoch: 29
no_aug_epoch: 8

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: [4, 29, 50]
  collate_fn:
    mixup_epochs: [4, 29]
    stop_epoch: 50

DFINETransformer:
  query_select_method: cost_aware
  query_select_alpha: 1e-06
  query_select_beta: 0.2
  query_select_gamma: 0.0
  query_select_use_gt: true
  query_select_gt_stop_epoch: 58
  query_select_cost_mode: sum
