__include__: [
  './dfine_hgnetv2_s_coco.yml',
  '../base/deim.yml'
]

output_dir: ./outputs/deim_s_cmqs
find_unused_parameters: true

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0002
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 132
flat_epoch: 64
no_aug_epoch: 12

train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: [4, 64, 120]
  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120

DFINETransformer:
  query_select_method: cost_aware
  query_select_alpha: 1.0
  query_select_beta: 0.2
  query_select_gamma: 0.2
  query_select_use_gt: true
  query_select_gt_stop_epoch: 24
  query_select_cost_mode: sum
